lib/gestaoFinanceira_web/router.ex
defmodule GestaoFinanceiraWeb.Router do
  use GestaoFinanceiraWeb, :router

  import GestaoFinanceiraWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GestaoFinanceiraWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GestaoFinanceiraWeb do
    pipe_through :browser

    get "/", UserSessionController, :new
    resources "/finances", FinanceController
  end

  # Other scopes may use custom stacks.
  # scope "/api", GestaoFinanceiraWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GestaoFinanceiraWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", GestaoFinanceiraWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", GestaoFinanceiraWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", GestaoFinanceiraWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/gestaoFinanceira_web/controllers/user_session_controller.ex
defmodule GestaoFinanceiraWeb.UserSessionController do
  use GestaoFinanceiraWeb, :controller

  alias GestaoFinanceira.Account
  alias GestaoFinanceiraWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Account.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/gestaoFinanceira_web/views/user_session_view.ex
defmodule GestaoFinanceiraWeb.UserSessionView do
  use GestaoFinanceiraWeb, :view
end

lib/gestaoFinanceira_web/templates/user_session/new.html.heex
<%= if @error_message do %>
    <div class="alert alert-danger" style="margin-top:1rem;height:3.2rem; width:14rem;margin-left:27rem;">
      <p><%= @error_message %></p>
    </div>
  <% end %>
<div class="container" 
     style=
     "margin-left: 24rem;
      margin-top: 3rem;
      background-color: #e3f2fd;
      border-radius:1rem;
      width:21.5rem;
      height:21rem;
     "
>
<h1 style="margin-left:6rem;">Log in</h1>

<.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>

<form >
  <div class="mb-3" style="margin-top:2rem;">
    <label style="margin-right:2.5rem;margin-left:1rem;" for="exampleInputEmail1" class="form-label"><%= label f, :email %></label>
    <%= email_input f, :email, required: true %>
  </div>

  <div class="mb-3" >
    <label style="margin-right:0.8rem; margin-left:1rem;"for="exampleInputPassword1" class="form-label"><%= label f, :password %></label>
    <%= password_input f, :password, required: true %>
  </div>

  <button type="submit" class="btn btn-primary" style="width:8rem;margin-left:6.4rem;margin-top:1rem; margin-bottom:1.5rem;">Submit</button>
</form>
</.form>

<button type="submit" class="btn btn-light" style="margin-right:1rem;background-color:white;border-color:blue;border-width:0.1rem;">
  <%= link "Register", to: Routes.user_registration_path(@conn, :new) %>
</button> |
<button type="submit" class="btn btn-light" style="margin-left:1rem;background-color:white;border-color:blue;border-width:0.1rem;">
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
</button>

</div>